version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page Template
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "Repository"
  link:      "https://github.com/rfauzan46/os212"
- navbar:    "Logs"
  link:      "/TXT/mylog.txt"
title:       "M. Rizki Fauzan - OS212"
lang:        "en-US"
author:      "Muhammad Rizki Fauzan"
address:     "Somewhere in the Universe."
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://template.vlsm.org/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ThisIsHowMeDoIt/template"


